/*DROP DATABASE ETEC_FERIADOS;*/

CREATE DATABASE ETEC_FERIADOS
GO

USE ETEC_FERIADOS;
GO

CREATE TABLE TBL_FERIADOS
(ID_FERIADO		BIGINT	 PRIMARY KEY IDENTITY,
TX_NOME			VARCHAR(50)	 NOT NULL,
DATA_FERIADO	DATE		 NOT NULL,
TP_FERIADO		VARCHAR(30)  NOT NULL
);
GO

INSERT INTO TBL_FERIADOS (TX_NOME, DATA_FERIADO, TP_FERIADO) VALUES
('Dia de Nsa Senhora Aparecida','2018-10-12','Feriado Nacional');
INSERT INTO TBL_FERIADOS (TX_NOME, DATA_FERIADO, TP_FERIADO) VALUES
('Independência do Brasil','2018-09-07','Feriado Nacional');
INSERT INTO TBL_FERIADOS (TX_NOME, DATA_FERIADO, TP_FERIADO) VALUES
('Dia da Revolução Constitucionalista','2018-07-09','Feriado Estadual');
INSERT INTO TBL_FERIADOS (TX_NOME, DATA_FERIADO, TP_FERIADO) VALUES
('Dia do Professor','2018-10-15','Facultativo');

SELECT * FROM TBL_FERIADOS;


